export enum ErrorCode {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  VALIDATION_ERROR = 'VALIDATION_ERROR',

  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',

  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',

  CONFLICT = 'CONFLICT',
  BAD_REQUEST = 'BAD_REQUEST',

  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',

  INVALID_ACCOUNT = 'INVALID_ACCOUNT',
  ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND',

  ACCOUNT_ALREADY_ARCHIVED = 'ACCOUNT_ALREADY_ARCHIVED',
}
