export enum ErrorCode {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  VALIDATION_ERROR = 'VALIDATION_ERROR',

  UNAUTHORIZED = 'UNAUTHORIZED',

  FORBIDDEN = 'FORBIDDEN',

  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',

  CONFLICT = 'CONFLICT',

  BAD_REQUEST = 'BAD_REQUEST',
}
